language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    # - os: osx
    #   osx_image: xcode7.2
    #   language: generic

addons:
  apt:
    packages:
      - build-essential
      - gdb
      - lldb-3.6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; brew install python ; fi

install:
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install mock pexpect nose ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install mock pexpect nose  --user; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install . ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install . --user; fi
  - ./install.sh -u -s

script:
  - python --version
  - mkdir ~/.voltron
  - echo '{"general":{"debug_logging":true}}' >~/.voltron/config
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python -m nose -sv tests/gdb_cli_tests.py ; fi
  - python -m nose -sv tests/lldb_cli_tests.py
